var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                     o                          ",
   "                                              o     xx      xx                  ",
   "                                    o o      xx                  xxxxx          ",
   "                                                                 xxxxx          ",
   "                                   xxxxx                                      o ",
   "   @                               x!!!x                                     xx ",
   "  xx                          o    xxvxx                                        ",
   "  x                          xx                                                 ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                             xxxxx           ",
   "  xxxxxxxxxxxx  xxxxxxxxxxx                               xxxxxxx   x           ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                      ",                              
   "                                                                                                      ",                                 
   "                                                                                                      ",                            
   "                                                                                                      ",                             
   "                                                                                                      ",                                    
   "                                                                                                      ",                               
   "                                                                                                      ",                                                                                      
   "                                                                                                      ",                               
   "                                                                                                      ",                                   
   "                                                                                                      ",                             
   "                                                          xxxx                                        ",
   "                                                         xx!!xx                                       ",                              
   "                                                         xx!!xx                                       ",                              
   "                                    o                    xx!!xx                                       ",                                   
   "                                 xxxxx                    xvvx                                        ",                                  
   "                         o                                                                            ",                               
   "                    xxxxxx                                                                            ",                            
   "                                                                                                      ",                            
   "                                            xxxxxx                          o                         ",                               
   "       xxxxxx                                                          xxxxxxxx                       ",                                   
   "                                                                                                      ",                               
   "  @                                                                                                   ",                            
   " xx                                                    oo                                      o      ",                              
   " x                 xxxxxxxxxxxxxx                    xxxxxxxxxxxxxx                     xxxxxxxxxxxx  ",                            
   " x                                                                                                    ",                                  
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",             
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                        
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                          
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                              
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                               
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                               
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                                
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                             
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                      ",                              
   "                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",                                 
   "                xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                    ",                            
   "                xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                    ",                             
   "                xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                    ",                                    
   "                xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                    ",                               
   "                xxxxvvxxxxxxxvvvvxxxxxvvxxxxxvxxxxxxxxvvxxxxxxvvvvxxxxxxxxxxxxxxxx                    ",                                                                                      
   "                                                                                                      ",                               
   "                                                                                                      ",                                   
   "     @                                                                                                ",                             
   " xxxxxxxxx                                                                                            ",
   " xx                                                                                                   ",                              
   " xx                                                                                                   ",                              
   " xx                                                                                                   ",                                   
   " xx                                                                                                   ",                                  
   " xx                                                                                                   ",                               
   " xx                                                                    oo                             ",                            
   " xx                       o                                          xxxxxxx                          ",                            
   " xx                     xxxx                                  xxx                                     ",                               
   " xx                              xxxxxxxxxxxx                                                         ",                                   
   " xx           xxxx                                                                xxxx                ",                               
   " xx                                                 xxxxx                                         o   ",                            
   " xx                                                                                         xxxxxxxx  ",                              
   " x                                                                                                    ",                            
   " x                                                                                                    ",                                  
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",             
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                        
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                          
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                              
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                               
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                               
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                                
   " x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                             
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                       ",                              
   "                           xx        xx  xx  xxx  xx  xxx  xx  xxxxx  xxxxxx                           ",                            
   "                            xx  xx  xx   xx  xx x xx  xx x xx  xxx    xx xxx                           ",                                  
   "                              xx  xx     xx  xx  xxx  xx  xxx  xxxxx  xx   x                           ",                               
   "                                                                                                       ",
   "                                                                                                       ",
   "  @                                                                                                    ",                               
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                                
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                             
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
